### PR TITLE
Removed dead code

### LINKED ISSUE #87: Fail to build on Fedora 35 rawhide
Fedora 35 is under development, so it might be a bug in the setup, or it can be an early warning that will happen in a newer toolchain. Builds on Fedora 34 and Fedora 33.
```
g++ -c -pipe -std=c++1z -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DNDEBUG -fomit-frame-pointer -O2 -std=gnu++1z -w -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DUSE_QT_IN_BITCOIN -DHAVE_ENDIAN_H -DHAVE_DECL_HTOBE16 -DHAVE_DECL_HTOLE16 -DHAVE_DECL_BE16TOH -DHAVE_DECL_LE16TOH -DHAVE_DECL_HTOBE32 -DHAVE_DECL_HTOLE32 -DHAVE_DECL_BE32TOH -DHAVE_DECL_LE32TOH -DHAVE_DECL_HTOBE64 -DHAVE_DECL_HTOLE64 -DHAVE_DECL_BE64TOH -DHAVE_DECL_LE64TOH -DHAVE_DECL___BUILTIN_CLZL -DHAVE_DECL___BUILTIN_CLZLL -DGIT_COMMIT=\"\" -DENABLE_ZMQ -DHAVE_JEMALLOC_HEADERS -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Isrc -I/usr/include/qt5 -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o Util.o src/Util.cpp
/bin/sh: line 1: git: command not found
In file included from /usr/include/pthread.h:33,
                 from /usr/include/c++/11/x86_64-redhat-linux/bits/gthr-default.h:35,
                 from /usr/include/c++/11/x86_64-redhat-linux/bits/gthr.h:148,
                 from /usr/include/c++/11/ext/atomicity.h:35,
                 from /usr/include/c++/11/bits/basic_string.h:39,
                 from /usr/include/c++/11/string:55,
                 from /usr/include/qt5/QtCore/qbytearray.h:52,
                 from /usr/include/qt5/QtCore/QByteArray:1,
                 from src/ByteView.h:21,
                 from src/Util.h:21,
                 from src/Mixins.h:21,
                 from src/App.h:21,
                 from src/Util.cpp:19:
src/Util.cpp:66:48: error: call to non-'constexpr' function 'long int __sysconf(int)'
   66 | static constexpr unsigned PLATFORM_STACK_MIN = PTHREAD_STACK_MIN;
      |                                                ^~~~~~~~~~~~~~~~~
/usr/include/bits/pthread_stack_min-dynamic.h:24:17: note: 'long int __sysconf(int)' declared here
   24 | extern long int __sysconf (int __name) __THROW;
      |                 ^~~~~~~~~
make: *** [Makefile:1896: Util.o] Error 1
```

gcc-c++: 11.2.1
qt5-qtbase-devel: 5.15.2
glibc-devel: 2.34

Full build log: https://download.copr.fedorainfracloud.org/results/jonny/BitcoinCash/fedora-rawhide-x86_64/02404254-fulcrum/build.log.gz

### PR DESCRIPTION
**Pull request by hegjon**
Removed function Util::getPlatformMinimumThreadStackSize() + PLATFORM_STACK_MIN.

This also fixes #87

### CODE REVIEW

**Comment by cculianu** [comment]
Ah, ok sure. Can you please also amend this PR to delete the declaration of the function `getPlatformMinimumThreadStackSize` in `Util.h`?

File: src/Util.cpp [hunk 1]
```diff
@@ -60,67 +60,7 @@
 #include <mutex>
 #include <thread>
 
-#if __has_include(<pthread.h>) && !defined(Q_OS_WIN)
-// MacOS, Linux, etc
-#  include <pthread.h>
-static constexpr unsigned PLATFORM_STACK_MIN = PTHREAD_STACK_MIN;
```
Comment (cculianu) [inline src/Util.cpp:66]: You could also just change this like to:

```c++
static const unsigned PLATFORM_STACK_MIN = PTHREAD_STACK_MIN;
```

And it would also fix #87 .. without needing to delete all this code...

**Comment by hegjon** [comment]
> Ah, ok sure. Can you please also amend this PR to delete the declaration of the function `getPlatformMinimumThreadStackSize` in `Util.h`?

Forgot the declaration, updated the PR

File: src/Util.cpp (hunk 1 above)
Comment (hegjon) [reply src/Util.cpp:66]: Follow your instinct. I'm a guest that have a preference for removing code, I have no knowledge if this code is/will be useful.

**Comment by cculianu** [comment]
TBH since it's not used and is rather nasty (and probably fragile, as we have seen) -- it's probably best to remove. It was used before but is no longer used.

File: src/Util.cpp (hunk 1 above)
Comment (cculianu) [reply src/Util.cpp:66]: TBH since it's not used and is rather nasty (and probably fragile, as we have seen) -- it's probably best to remove. It was used before but is no longer used.
